// Generates migrations/0002_seed.sql from the deterministic demo-data generator.
// Run: npm run seed:generate  (output is byte-stable; commit the result)
import { createHash, pbkdf2Sync } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { generateShipments } from '../src/data/generator'
import { CARRIERS, CONSIGNEES, FORWARDERS, SHIPPERS } from '../src/data/constants'
import { iso, TODAY } from '../src/data/random'

const PBKDF2_ITERATIONS = 100000
const DEMO_PASSWORD = 'tidelane-demo'

const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : `'${v.replace(/'/g, "''")}'`
const n = (v: number | null | undefined): string => (v === null || v === undefined ? 'NULL' : String(v))

function passwordHash(email: string): string {
  // Salt derived from the email so regeneration is byte-identical.
  const salt = createHash('sha256').update(`tidelane-salt:${email}`).digest().subarray(0, 16)
  const hash = pbkdf2Sync(DEMO_PASSWORD, salt, PBKDF2_ITERATIONS, 32, 'sha256')
  return `pbkdf2$${PBKDF2_ITERATIONS}$${salt.toString('base64')}$${hash.toString('base64')}`
}

// --- Organizations -----------------------------------------------------------
interface Org {
  id: number
  name: string
  type: string
}
const orgs: Org[] = [{ id: 1, name: 'Tidelane', type: 'internal' }]
let orgId = 2
for (const s of SHIPPERS) orgs.push({ id: orgId++, name: s.name, type: 'shipper' })
for (const c of CONSIGNEES) orgs.push({ id: orgId++, name: c.name, type: 'consignee' })
for (const f of FORWARDERS) orgs.push({ id: orgId++, name: f.name, type: 'forwarder' })
for (const c of CARRIERS) orgs.push({ id: orgId++, name: c.name, type: 'carrier' })
const orgByName = new Map(orgs.map((o) => [o.name, o.id]))

// --- Users -------------------------------------------------------------------
const users = [
  { id: 1, email: 'yigal.tzfira@galco-intl.com', name: 'Yigal Tzfira', title: 'Managing Director', role: 'admin', org: 'Tidelane' },
  { id: 2, email: 'effi.mor@galco-intl.com', name: 'Effi Mor', title: 'Operations Specialist', role: 'ops', org: 'Tidelane' },
  { id: 3, email: 'ben.mor@galco-intl.com', name: 'Ben Mor', title: 'Supply Chain Analyst', role: 'viewer', org: 'Tidelane' },
  { id: 4, email: 'dana@atlaspolymers.demo', name: 'Dana Weiss', title: 'Export Manager', role: 'ops', org: 'Atlas Polymers Ltd' },
  { id: 5, email: 'amit@globalfreight.demo', name: 'Amit Shalev', title: 'Freight Coordinator', role: 'ops', org: 'GlobalFreight Partners' },
  { id: 6, email: 'pieter@northline.demo', name: 'Pieter van Dam', title: 'Import Planner', role: 'viewer', org: 'Northline Imports BV' },
  { id: 7, email: 'desk@meridianline.demo', name: 'Operations Desk', title: 'Carrier Operations', role: 'ops', org: 'Meridian Line' },
]

// --- SQL ---------------------------------------------------------------------
const now = iso(TODAY)
const out: string[] = ['-- Generated by scripts/generate-seed.ts — do not edit by hand.', '']

out.push(
  `INSERT INTO organizations (id, name, type) VALUES\n` +
    orgs.map((o) => `  (${o.id}, ${q(o.name)}, ${q(o.type)})`).join(',\n') +
    ';',
  '',
)

out.push(
  `INSERT INTO users (id, email, name, title, role, org_id, password_hash, active, created_at) VALUES\n` +
    users
      .map(
        (u) =>
          `  (${u.id}, ${q(u.email)}, ${q(u.name)}, ${q(u.title)}, ${q(u.role)}, ${orgByName.get(u.org)}, ${q(passwordHash(u.email))}, 1, ${q(now)})`,
      )
      .join(',\n') +
    ';',
  '',
)

out.push(
  `INSERT INTO user_settings (user_id, updated_at) VALUES\n` +
    users.map((u) => `  (${u.id}, ${q(now)})`).join(',\n') +
    ';',
  '',
)

const shipments = generateShipments()

for (const s of shipments) {
  out.push(
    `INSERT INTO shipments (id, booking_ref, origin_code, destination_code, via_code, lane_id, carrier_name, carrier_scac, vessel_name, vessel_imo, vessel_voyage, status, etd, eta, atd, incoterm, commodity, co2_tons, freight_cost_usd, on_time, progress, delay_reason, created_by, created_at) VALUES\n` +
      `  (${q(s.id)}, ${q(s.bookingRef)}, ${q(s.origin.code)}, ${q(s.destination.code)}, ${q(s.via?.code ?? null)}, ${q(s.laneId)}, ${q(s.carrier.name)}, ${q(s.carrier.scac)}, ${q(s.vessel.name)}, ${q(s.vessel.imo)}, ${q(s.vessel.voyage)}, ${q(s.status)}, ${q(s.etd)}, ${q(s.eta)}, ${q(s.atd ?? null)}, ${q(s.incoterm)}, ${q(s.commodity)}, ${n(s.co2Tons)}, ${n(s.freightCostUsd)}, ${s.onTime ? 1 : 0}, ${n(s.progress)}, ${q(s.delayReason ?? null)}, NULL, ${q(now)});`,
  )
  out.push(
    `INSERT INTO containers (shipment_id, position, number, type, seal_number, weight_kg, status, dd_risk_usd) VALUES\n` +
      s.containers
        .map((c, i) => `  (${q(s.id)}, ${i}, ${q(c.number)}, ${q(c.type)}, ${q(c.sealNumber)}, ${n(c.weightKg)}, ${q(c.status)}, ${n(c.ddRiskUsd)})`)
        .join(',\n') +
      ';',
  )
  out.push(
    `INSERT INTO milestones (shipment_id, position, key, label, location, planned, actual, status) VALUES\n` +
      s.milestones
        .map((m, i) => `  (${q(s.id)}, ${i}, ${q(m.key)}, ${q(m.label)}, ${q(m.location)}, ${q(m.planned)}, ${q(m.actual ?? null)}, ${q(m.status)})`)
        .join(',\n') +
      ';',
  )
  out.push(
    `INSERT INTO documents (id, shipment_id, type, name, status, uploaded_by, updated_at) VALUES\n` +
      s.documents
        .map((d) => `  (${q(d.id)}, ${q(s.id)}, ${q(d.type)}, ${q(d.name)}, ${q(d.status)}, ${q(d.uploadedBy)}, ${q(d.updatedAt)})`)
        .join(',\n') +
      ';',
  )
  if (s.comments.length) {
    out.push(
      `INSERT INTO comments (id, shipment_id, author, role, text, at) VALUES\n` +
        s.comments
          .map((c) => `  (${q(c.id)}, ${q(s.id)}, ${q(c.author)}, ${q(c.role)}, ${q(c.text)}, ${q(c.at)})`)
          .join(',\n') +
        ';',
    )
  }
  out.push(
    `INSERT INTO shipment_parties (id, shipment_id, org_id, name, role, contact) VALUES\n` +
      s.parties
        .map((p) => `  (${q(p.id)}, ${q(s.id)}, ${n(orgByName.get(p.name) ?? null)}, ${q(p.name)}, ${q(p.role)}, ${q(p.contact)})`)
        .join(',\n') +
      ';',
    '',
  )
}

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'migrations', '0002_seed.sql')
writeFileSync(outPath, out.join('\n') + '\n')
console.log(`Wrote ${outPath}: ${orgs.length} orgs, ${users.length} users, ${shipments.length} shipments`)
